### PR TITLE
Updated requirements.txt

### PR DESCRIPTION
**Pull request by MikkelDK**
**THIS IS UPDATED VERSION!**

### CODE REVIEW

**Comment by retropc** [comment]
why?

that's an implicit dependency

**Comment by MikkelDK** [comment]
Well it works with the updated version. It don't know here, with the version from your github.

**Comment by retropc** [comment]
please elaborate on "don't work"

it works fine for me, and for the CI system: https://travis-ci.org/qwebirc/qwebirc

**Comment by retropc** [comment]
I fixed this in master (though a slightly different way)

**Pull request closed without merging**
